### ISSUE TITLE
Source of {sf} cheatsheet

### ISSUE THREAD

**Issue by statnmap** [ryangarnett/cheatsheat#1]
Hi Ryan,
Thank you for the {sf} cheatsheet.  
Would be ok to send me the ppt version of this cheatsheet, so that I can translate it in French in a proper way ?  
Thank you

**Comment by ryangarnett** [comment]
Hi Sebastian,

Sorry for the delay in my response. I created the cheatsheet in Inkscape as
an SVG, not PPT. Are you able to work with that?

Ryan

**Comment by statnmap** [comment]
Hi Ryan,
This is way better !
You could even share this svg on your github. I think cheatsheet templates realised with an open-source software is more in the R philosophy...

**Comment by ryangarnett** [comment]
Hi Sebastien,

I totally agree with you, an open source open knowledge sharing product
should be created in open source first. The SVG is on my work computer, I
will send it to you tomorrow when I am at work, and add it to my Github
page.

Thanks for the interest in the cheat sheet, and for contributing to the
community!

Ryan

**Comment by ryangarnett** [comment]
Hi Sebastien,

Attached is the SVG version of the cheatsheet, page 1 and page two. I have
also added them to my GitHub page https://github.com/ryangarnett/rSpatial

Thanks for converting the cheatsheet,

Ryan

**Comment by statnmap** [comment]
Perfect. Thanks.
